<div class="flow-title"><span class="eyebrow dark">FINALIZAR COMPRA</span><h1>PAGO Y <em>ENTREGA.</em></h1><div><span>1 CARRITO</span><i></i><b>2 PAGO SEGURO</b><i></i><span>3 DESCARGA</span></div></div>
<?php if(!empty($_SESSION['error'])):?><div class="demo-note"><?=htmlspecialchars($_SESSION['error']);unset($_SESSION['error']);?></div><?php endif;?>
<div class="checkout-layout"><form method="post"><input type="hidden" name="_token" value="<?=csrf()?>"><h2>01 · DATOS DE ENTREGA</h2><div class="fields"><label>Nombre completo<input name="name" required value="<?=htmlspecialchars($customer['name']??'')?>"></label><label>Correo electrónico<input name="email" type="email" required value="<?=htmlspecialchars($customer['email']??'')?>" <?=$customer?'readonly':''?>></label><label>Teléfono<input name="phone" required value="<?=htmlspecialchars($customer['phone']??'')?>"></label><label>RUT<input name="rut" required value="<?=htmlspecialchars($customer['rut']??'')?>"></label></div>
<?php if(!$customer):?><div class="create-account"><label><input id="createAccount" type="checkbox" name="create_account"> <span><b>CREAR UNA CUENTA</b><small>Podrás revisar pedidos, estados y descargar nuevamente tus compras.</small></span></label><div id="accountPassword" hidden><label>CONTRASEÑA PARA TU CUENTA<input type="password" name="account_password" minlength="8"></label></div></div><?php else:?><div class="flow-security"><b>✓ COMPRA ASOCIADA A TU CUENTA</b><span>Este pedido aparecerá automáticamente en “Mi cuenta”.</span></div><?php endif;?>
<h2>02 · MÉTODO DE PAGO</h2>
<?php if($gateways):?><div class="payment gateway-payment-options">
 <?php $first=true;foreach($gateways as $key=>$gateway):?>
 <label class="gateway-choice is-<?=$key?>"><input type="radio" name="payment_provider" value="<?=$key?>" <?=$first?'checked':''?> required><span class="gateway-radio"></span><span class="gateway-copy"><b><?=$key==='transbank'?'WEBPAY PLUS':htmlspecialchars(strtoupper($gateway['name']))?></b><small><?=htmlspecialchars($gateway['description'])?></small></span><strong><?=$key==='transbank'?'TRANSBANK':'PAGO SEGURO'?></strong></label>
 <?php $first=false;endforeach;?>
</div><label class="terms"><input type="checkbox" required> Acepto los términos de compra.</label><button>IR A PAGAR <span><?=money((int)array_sum(array_column($items,'price')))?></span> →</button>
<?php else:?><div class="payment-unavailable"><b>PASARELAS TEMPORALMENTE INACTIVAS</b><p>La compra no puede continuar hasta que el administrador active Flow o Transbank.</p></div><button type="button" disabled>COMPRA NO DISPONIBLE</button><?php endif;?></form>
<aside class="summary"><span>TU PEDIDO</span><?php foreach($items as $i):$label=$i['type']==='set'?'Set completo':($i['type']==='pack'?'Combo personalizado · '.$i['photos_count'].' fotos':'Foto individual');?><div class="order-row"><img src="<?=preview_url(['id'=>$i['cover_id']??$i['photo_id'],'preview_path'=>$i['preview_path']])?>"><span><b><?=htmlspecialchars($i['title'])?></b><small><?=$label?></small></span><strong><?=money($i['price'])?></strong></div><?php endforeach;?><p class="total">TOTAL <b><?=money((int)array_sum(array_column($items,'price')))?></b></p></aside></div>
<script>document.getElementById('createAccount')?.addEventListener('change',event=>{const box=document.getElementById('accountPassword');box.hidden=!event.target.checked;box.querySelector('input').required=event.target.checked})</script>
