<?php
$heroDefaults=['eyebrow'=>'AstroSport · Archivo deportivo','title'=>'Fotografía que captura la intensidad del deporte.','description'=>'Encuentra tu evento, selecciona tus imágenes y recíbelas en alta resolución.','search_placeholder'=>'Busca por deporte, evento o ciudad','button_text'=>'Buscar','background_url'=>'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1900&q=90'];
$hero=array_merge($heroDefaults,is_array($hero??null)?$hero:[]);
$heroTitle=trim($hero['title'].' '.($hero['highlight']??''));
$heroBackground=preg_match('~^https?://~i',(string)$hero['background_url'])?$hero['background_url']:url('hero-imagen?v='.rawurlencode((string)($hero['updated_at']??'')));
?>
<section class="reference-hero" id="inicio" style="--hero-image:url('<?=htmlspecialchars($heroBackground)?>')">
 <div class="reference-shade"></div><div class="reference-hero-copy"><span class="reference-eyebrow"><?=htmlspecialchars($hero['eyebrow'])?></span><h1><?=htmlspecialchars($heroTitle)?></h1><p><?=htmlspecialchars($hero['description'])?></p>
 <form class="reference-search" action="<?=url()?>" method="get"><span aria-hidden="true">⌕</span><input name="q" value="<?=htmlspecialchars($_GET['q']??'')?>" placeholder="<?=htmlspecialchars($hero['search_placeholder'])?>"><button><?=htmlspecialchars($hero['button_text'])?></button></form></div>
</section>
<section class="reference-archive" id="fotos">
 <div class="reference-archive-title"><div><span class="reference-kicker">Compra tus fotografías</span><h2>Últimas coberturas</h2></div><small><?=count($catalogSets)?> colecciones disponibles</small></div>
 <div class="reference-categories"><a class="<?=empty($categorySlug)?'active':''?>" href="<?=url('#fotos')?>">Todas</a><?php foreach($categories as $category):?><a class="<?=$categorySlug===$category['slug']?'active':''?>" href="<?=url('?category='.rawurlencode($category['slug']).'#fotos')?>"><?=htmlspecialchars($category['name'])?></a><?php endforeach;?></div>
 <form class="reference-filters" action="<?=url()?>" method="get"><label><span>Buscar archivo</span><input name="q" value="<?=htmlspecialchars($_GET['q']??'')?>" placeholder="Número, set o evento"></label><label><span>Ordenar</span><select name="orden"><option>Recientes</option><option>Nombre</option></select></label><button>Aplicar filtros</button><?php if(!empty($_GET['q'])):?><a href="<?=url('#fotos')?>">Limpiar</a><?php endif;?></form>
 <?php if($catalogSets):?><div class="reference-wall"><?php foreach($catalogSets as $index=>$set):?><?php $slides=$setPreviews[$set['id']]??[];$cover=$slides[0]??['id'=>$set['cover_id'],'preview_path'=>$set['preview_path']];?>
 <article class="reference-card"><a class="reference-photo <?=['landscape','portrait','square'][$index%3]?>" href="<?=url('foto?id='.$set['cover_id'])?>"><img src="<?=preview_url($cover)?>" alt="<?=htmlspecialchars($set['name'])?>"><b><?=htmlspecialchars($set['event_name'])?></b><span>Ver galería →</span></a><div class="reference-caption"><p><?=(int)$set['photos_count']?> fotografías<?=!empty($set['bib_number'])?' · Nº '.htmlspecialchars($set['bib_number']):''?></p><h3><?=htmlspecialchars($set['name'])?></h3><div><strong>Desde <?=money((int)$set['individual_price'])?></strong><a href="<?=url('foto?id='.$set['cover_id'])?>">Seleccionar</a></div></div></article>
 <?php endforeach;?></div><?php else:?><div class="reference-empty"><h3>No encontramos fotografías.</h3><a href="<?=url('#fotos')?>">Ver todo el archivo</a></div><?php endif;?>
</section>
<section class="reference-benefits"><div><b>Entrega digital HD</b><span>Archivos en alta resolución</span></div><div><b>Compra protegida</b><span>Confirmación antes del pago</span></div><div><b>Uso personal</b><span>Licencia incluida por fotografía</span></div></section>
<section class="reference-contact"><div><span>Para clubes y organizaciones</span><h2>¿Necesitas cobertura para tu evento?</h2></div><a href="mailto:contacto@astrosport.cl">Solicitar propuesta →</a></section>
